### ISSUE TITLE
I quickly fixed it, so it doesn't work anymore

### ISSUE THREAD

**Issue by andrin-n-dream** [CodeStix/airconsole-crack#1]
... but thanks for pointing this simple hack out. much appreciated.

Here is an AirConsole Hero Code for one year: 969 824 632 1

Just enter it in the AirConsole App as the connect code and you'll be a hero for year.
Whoever uses the code first can claim it.

**Comment by CodeStix** [comment]
Woah! Thanks for the one year hero!

**Comment by GulameRaza** [comment]
hey looking out for 1 year...can u help me??
my gmail id sayedjasim007@gmail.com
